# Generated by Django 6.0.2 on 2026-02-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='products.product'),
        ),
        migrations.AddField(
            model_name='productrecommendation',
            name='recommended_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productrecommendation',
            unique_together={('base_product', 'recommended_product', 'reason')},
        ),
    ]
