# Generated by Django 6.0.2 on 2026-02-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Razorpay Webhook Log',
                'verbose_name_plural': 'Razorpay Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='Payment ID')),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('net_banking', 'Net Banking'), ('upi', 'UPI'), ('wallet', 'Wallet')], max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Currency')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Gateway Response')),
                ('captured', models.BooleanField(default=False, verbose_name='Captured')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Captured At')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
